server:
  port: 8010
spring:
  datasource:
    url: jdbc:mysql://localhost:3307/user
    username: root
    password: 123

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  application:
    name: USER-SERVICE

  eureka:
    instance:
      prefer-Ip-Address: true
