server:
  port: 8761
eureka:
  instance:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://user:password@localhost:8761/eureka

spring:
  application:
    name: EUREKA-SERVER
  #security:
  #  user:
   #   name: user
    #  password: password